### PR TITLE
Fix line drawing interop exception

### PR DESCRIPTION
**Pull request by pmensik**

### CODE REVIEW

**Comment by dotemacs** [comment]
Hello @pmensik 

thank you for taking the time to create this PR.

I can see this issue: https://github.com/dotemacs/pdfboxing/issues/50 and I take it that it's a response to that.

But can you put together a test that demonstrates this scenario and how it resolves it, because I can't just include merge this in as is.

Thank you

**Comment by pmensik** [comment]
Hey @dotemacs 

I've added the test, sorry it took me so long, I kinda forgot about it :)

Regards,

Petr

**Comment by dotemacs** [comment]
Thank you Petr

**Comment by dotemacs** [comment]
I haven't forgotten about this, I'll tackle it! Thanks

**Comment by dalanicolai** [comment]
Will this fix be merged soon? I am completely new to clojure so I am not very familiar with workarounds. I installed pdfboxing via the `deps.edn` file with the lines:
```
{:deps
 {pdfboxing/pdfboxing {:mvn/version "0.1.14"}}}
```
I am trying the draw-line example from the README and I am getting the following error:
```
Execution error (IllegalArgumentException) at pdfboxing.draw/get-page (draw.clj:13).
No matching field found: getAllPages for class org.apache.pdfbox.pdmodel.PDDocumentCatalog
```

**Comment by dotemacs** [comment]
Hi, if you don’t hear from me about this by tomorrow, please bug me! Thanks

**Comment by dotemacs** [comment]
Hey @dalanicolai 

> Will this fix be merged soon?

I pulled the changes from @pmensik and you can try to use them via:

```clojure
{:deps
 {pdfboxing/pdfboxing {:git/url "https://github.com/dotemacs/pdfboxing.git" 
                       :sha "cb440d7488eb625e1a5975111e739fab13400067"}}}
```

Just to be doubly sure, can you confirm that the above works for you?
Once you do, I'll cut a new release.

Thanks

**Comment by dalanicolai** [comment]
Man that's fast! Thanks. Unfortunately it does not work yet. I get the following error:
```
Error building classpath. Manifest type not detected when finding deps for pdfboxing/pdfboxing in coordinate {:git/url "https://github.com/dotemacs/pdfboxing.git", :sha "2d2f0ff81c31d2a8df3b82fce91468143384b77c"}
```
I found a possible solution [here](https://ask.clojure.org/index.php/8507/failure-on-github-import-via-deps), but did not try it.

**Comment by dotemacs** [comment]
Hey @dalanicolai 

I just pushed a new release, please try that:

https://clojars.org/pdfboxing/versions/0.1.15.1-SNAPSHOT

**Comment by dotemacs** [comment]
Since I pulled in these two commits that contain your changes @pmensik, which I've slightly squashed:

- 56a8e335c8a2a46c72c21024e257bc9b3a605c82
- 2d2f0ff81c31d2a8df3b82fce91468143384b77c

I'll say that your changes are appreciated and have been included in the source tree. So I'll close this PR.

@dalanicolai if you still experience an issue, maybe open a different issue to discuss it further.

Thank you both

**Comment by dalanicolai** [comment]
It works perfectly fine now. Thanks a lot!

**Pull request closed without merging**
